### ISSUE TITLE
Issue with adding span_marker pipe within spaCy

### ISSUE THREAD

**Issue by Rao-Sanjayy** [tomaarsen/SpanMarkerNER#13]
ValueError                                Traceback (most recent call last)
[<ipython-input-2-c526aa1bc9eb>](https://localhost:8080/#) in <cell line: 6>()
      4 # Load the spaCy model
      5 nlp = spacy.load("en_core_web_sm")
----> 6 nlp.add_pipe("span_marker", config={"model": "tomaarsen/span-marker-roberta-large-ontonotes5"})
      7 
      8 # Feed some text through the model to get a spacy Doc

1 frames
[/usr/local/lib/python3.10/dist-packages/spacy/language.py](https://localhost:8080/#) in create_pipe(self, factory_name, name, config, raw_config, validate)
    658                 lang_code=self.lang,
    659             )
--> 660             raise ValueError(err)
    661         pipe_meta = self.get_factory_meta(factory_name)
    662         # This is unideal, but the alternative would mean you always need to

ValueError: [E002] Can't find factory for 'span_marker' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, doc_cleaner, parser, beam_parser, lemmatizer, trainable_lemmatizer, entity_linker, ner, beam_ner, entity_ruler, tagger, morphologizer, senter, sentencizer, textcat, spancat, spancat_singlelabel, future_entity_ruler, span_ruler, textcat_multilabel, en.lemmatizer

Package versions:
spacy == 3.5.3 (did not work with 3.5.2 as well)
span_marker == 1.2.1

**Comment by tomaarsen** [comment]
If this issue persists (e.g. in Google Colab it seems to persist), then you can always add `import span_marker` and it'll work.

**Comment by Rao-Sanjayy** [comment]
Thanks for helping out. Really appreciate it.
