### ISSUE TITLE
How to make this work for overlapping entities?

### ISSUE THREAD

**Issue by seekingpeace** [tomaarsen/SpanMarkerNER#21]
Hi tom, i was wondering how could i make this work for overlapping spans for different entity types and how to extend this to relations extraction as well. 
Any help or direction would be super helpful.

**Comment by tomaarsen** [comment]
Hello!

I'm afraid that this project only works with "flat" NER, i.e. non-nested spans. The approach could be extended to support nested NER, but it would require some changes in both the preprocessing before training and predictions after training.

- Tom Aarsen
