### ISSUE TITLE
Cannot train BILOU scheme with no singletons

### ISSUE THREAD

**Issue by david-waterworth** [tomaarsen/SpanMarkerNER#30]
The `AutoLabelNormalizer` infers the scheme based on the presence of all the tag prefixes - i.e. BILOU is assumed if there's at least one of each of ['B','I','L','O','U']. There doesn't appear to be any way of passing a specific `LabelNormalizer` to the trainer.

My issue with this is that my dataset contains only BILO - i.e., there are no singletons. But the nature of my problem means I need to use a scheme that has B and L tags.

Because my dataset has no U tags SpanMarker errors since the set BILO doesn't match any of cases that `AutoLabelNormalizer` checks, i.e. perhaps allow a LabelNormalizer to be passed as an argument or relax the conditions i..e

        if (tags == set("BILOU")) or (tags == set("BILO")):
            return LabelNormalizerBILOU(config)

**Comment by tomaarsen** [comment]
I think that's very sensible! I'll create a pull request for you, and create a way for you to install it. Perhaps you could then notify me whether the changes in the pull request solve your problem? I don't currently have a BILO dataset available, so I can't easily test it.

- Tom Aarsen
