### ISSUE TITLE
Hugging Face Space URL not working for FewNERD fine-tuned model 

### ISSUE THREAD

**Issue by alvarobartt** [tomaarsen/SpanMarkerNER#32]
Hi here @tomaarsen!

## Description

It seems that the Hugging Face Space linked as [🤗 Space](https://tomaarsen-span-marker-bert-base-fewnerd-fine-super.hf.space/) is not working as it throws an HTTP 404 error code, and it seems is no longer in your Hugging Face Hub account.

So I just wanted to point that out in case you want to have a running example besides the Free Inference API, otherwise I guess you're good removing it!

**Comment by tomaarsen** [comment]
Oh, oops. I forgot I still had this link. The Space stopped working at some point when Gradio updated, so I shut it down. After all, the free inference API is already sufficient I think.

- Tom Aarsen

**Comment by tomaarsen** [comment]
Fixed via ce22087f2525f826850d222445cec4fd5e476ff0
