### ISSUE TITLE
amazing works but minimum token ?

### ISSUE THREAD

**Issue by noctetemp** [tomaarsen/SpanMarkerNER#5]
Hello 
it is really an amazing work, but I wonder is there any minimum number of token required? 
when I tried inference on a short sentence or question, it just returned an empty JSON.

**Comment by tomaarsen** [comment]
Hello!

There shouldn't be a minimum number of tokens required. However, the model will respond best to sentences that match roughly the sentences that were used in training. For example, I believe that the average sentence of the training set for my FewNERD models was 22 words, and all sentences end with a dot. I've noticed that this has led the model to never or rarely consider the last word to be a part of an entity. 
For example, a sentence with a dot:
![image](https://user-images.githubusercontent.com/37621491/236747264-4c279eb8-a51a-4b85-aeed-3a294255ae4d.png)
And the same sentence without one:
![image](https://user-images.githubusercontent.com/37621491/236748022-b68c0688-f1bd-4a48-8a2c-c2d7470b3916.png)

Perhaps in the same way, some shorter sentences are also problematic. However, I can't quickly get the model to perform quickly with short sentences:
![image](https://user-images.githubusercontent.com/37621491/236748328-9e818448-dadc-4a67-841d-356bc3cc62d9.png)

(I used [this model](https://huggingface.co/tomaarsen/span-marker-bert-base-fewnerd-fine-super) for my tests)

- Tom Aarsen

**Comment by noctetemp** [comment]
```python
from span_marker import SpanMarkerModel

model = SpanMarkerModel.from_pretrained("tomaarsen/span-marker-bert-base-fewnerd-fine-super")

questions = ["Did the queen finish her speech?", "Did the teacher assign homework today?",
             "Did the chef use fresh ingredients in the recipe?",
             "Did the doctor prescribe any medication for the illness?",
             "Did the construction workers complete the building on time?", "Did the pilot land the plane safely?",
             "Did the artist create a new masterpiece for the exhibition?",
             "Did the author write the sequel to the popular novel?",
             "Did the athlete break any records in the competition?"]

for question in questions:
    result = model.predict(question)
    print(result)

answers = ["The queen finished her speech.", "The teacher assigned homework today.",
           "The chef used fresh ingredients in the recipe.",
           "The doctor prescribed medication for the illness.",
           "The construction workers completed the building on time.", "The pilot landed the plane safely.",
           "The artist created a new masterpiece for the exhibition.",
           "The author wrote the sequel to the popular novel.",
           "The athlete did not break any records in the competition."]

for answer in answers:
    result = model.predict(answer)
    print(result)

``` /

none of it worked and it was all empty jsons. 

but then I added few words and it started to work : 

```python
modified_questions = [
    "Did the queen finish her speech on climate change at the UN General Assembly?",
    "Did the teacher assign any challenging homework on algebraic equations today?",
    "Did the Michelin-starred chef use fresh organic ingredients in the recipe for the signature dish?",
    "Did the doctor prescribe any effective medication for the rare autoimmune disease?",
    "Did the skilled construction workers complete the 50-storey skyscraper on time and within budget?",
    "Did the experienced pilot safely land the commercial plane during a thunderstorm and strong crosswinds?",
    "Did the world-renowned artist create a new breathtaking masterpiece for the prestigious exhibition at the Louvre?",
    "Did the best-selling author finally write the highly anticipated sequel to the popular crime thriller novel?",
    "Did the talented athlete break any world records in the highly competitive Olympic Games?"
]

for question in modified_questions:
    result = model.predict(question)
    print(result)

``` 

![output](https://user-images.githubusercontent.com/53593281/236776854-d7fd9e85-4339-472f-8292-92523a310936.jpg)

Anyway, thank you a lot for your answer and your great work. 
I will continue to look into it and let you know if I have any findings.

**Comment by tomaarsen** [comment]
I think I'm understanding the issue now - Named Entity Recognition (NER) models only recognize `named entities`, i.e. *names of things* like `Tom`, `SpanMarker`, `Olympic Games`, `Louvre`, `England`, `Lake Ontario`. The goal of the task is to identify the category of the *thing* is that is being named. This means that regular nouns/noun pairs like `talented athlete` or `best-selling author` are not identified, while the model recognizes that `UN General Assembly` has the category of `organization-government/governmentagency` and `Michelin` is a `building-restaurant`.

That is why it only picked up e.g. UN General Assembly and Michelin, those are simply the only "real" named entities in your sentences.

I hope that helps clear it up.

- Tom Aarsen

**Comment by tomaarsen** [comment]
I hope this has answered your question. I'll close this for now, feel free to respond again or open another issue if you wish.
