### ISSUE TITLE
[Deps Bug] ImportError: cannot import name 'DatasetFilter' from 'huggingface_hub' 

### ISSUE THREAD

**Issue by logan-markewich** [tomaarsen/SpanMarkerNER#64]
I think huggingface_hub updated, and now span marker doesn't work without manually restricting the version of huggingface_hub

In a fresh venv run `pip install span-marker`

Then, running `from span_marker import SpanMarkerModel` produces the error in the title

Probably should fix the import and adjust the dependencies

**Comment by mertsengil** [comment]
pip install huggingface_hub==0.23.5

**Comment by tomaarsen** [comment]
Merged, fixed some other outstanding integration/deprecation issues, and released this.
Apologies for the looong wait, I should have prioritized this over my other work months ago.

https://pypi.org/project/span-marker/1.6.0/

- Tom Aarsen
