### ISSUE TITLE
Entity type

### ISSUE THREAD

**Issue by skwskwskwskw** [tomaarsen/SpanMarkerNER#7]
Hi,

Appreciate the amazing work. Is there a list of entity to be detected with the pretrained model?

Thanks.

**Comment by tomaarsen** [comment]
Hello!

Yes, the models that I've already trained at this time are:
* [tomaarsen/span-marker-bert-base-fewnerd-fine-super](https://huggingface.co/tomaarsen/span-marker-bert-base-fewnerd-fine-super): Trained on finegrained FewNERD that has these labels:
```
['art-broadcastprogram', 'art-film', 'art-music', 'art-other', 'art-painting', 'art-writtenart', 'building-airport', 'building-hospital', 'building-hotel', 'building-library', 'building-other', 'building-restaurant', 'building-sportsfacility', 'building-theater', 'event-attack/battle/war/militaryconflict', 'event-disaster', 'event-election', 'event-other', 'event-protest', 'event-sportsevent', 'location-GPE', 'location-bodiesofwater', 'location-island', 'location-mountain', 'location-other', 'location-park', 'location-road/railway/highway/transit', 'organization-company', 'organization-education', 'organization-government/governmentagency', 'organization-media/newspaper', 'organization-other', 'organization-politicalparty', 'organization-religion', 'organization-showorganization', 'organization-sportsleague', 'organization-sportsteam', 'other-astronomything', 'other-award', 'other-biologything', 'other-chemicalthing', 'other-currency', 'other-disease', 'other-educationaldegree', 'other-god', 'other-language', 'other-law', 'other-livingthing', 'other-medical', 'person-actor', 'person-artist/author', 'person-athlete', 'person-director', 'person-other', 'person-politician', 'person-scholar', 'person-soldier', 'product-airplane', 'product-car', 'product-food', 'product-game', 'product-other', 'product-ship', 'product-software', 'product-train', 'product-weapon']
```
* [tomaarsen/span-marker-roberta-large-fewnerd-fine-super](https://huggingface.co/tomaarsen/span-marker-roberta-large-fewnerd-fine-super): Trained on finegrained FewNERD, i.e. the same labels as the one above.
* [tomaarsen/span-marker-bert-tiny-fewnerd-coarse-super](https://huggingface.co/tomaarsen/span-marker-bert-tiny-fewnerd-coarse-super): Trained on coarse-grained FewNERD that has these labels:
```
['art', 'building', 'event', 'location', 'organization', 'other', 'person', 'product']
```
* [tomaarsen/span-marker-bert-tiny-conll03](https://huggingface.co/tomaarsen/span-marker-bert-tiny-conll03): Trained on CoNLL2003 that has these labels:
```
['PER', 'ORG', 'LOC', 'MISC']
```
Although the last 2 are primarily trained to be used in my [tests](https://github.com/tomaarsen/SpanMarkerNER/blob/66b7f54c1128ad9456e4dff5f4ac7f3aaf4b785c/tests/conftest.py#L32).

With SpanMarker you can also train your own models using e.g. `bert-base-cased`, and then you can use whatever labels you want. 

I hope that clears it up a bit :)

- Tom Aarsen

**Comment by tomaarsen** [comment]
I hope this has answered your question. I'll close this for now, feel free to respond again or open another issue if you wish.
